### ISSUE TITLE
Support gnustep-2.0 ABI in GSPrivateSymbolPath()

### ISSUE THREAD

**Issue by ngrewe** [gnustep/libs-base#106]
`GSPrivateSymbolPath` currently maps from classes into defining objects by looking for the `__objc_class_name_*` symbol. This fails with the gnustep-2.0 ABI, which uses `_OBJC_CLASS` as the prefix.

**Comment by rfm** [comment]
I've been working on 2.0 ABI support for the last week or so, and have added a simple fix for this, but you might do something better.  For instnce, I was wondering if it might make sense to check for both the expected prefix (depending on how base was compiled) *and* if that fails for the other possible prefix.  If we find the class using the wrong prefix, we could abort with an error message because we know we are somehow linked with code which was compiled for the wrong ABI.  I didn't do that because I don't know if it would really be useful (perhaps the linker or the runtime would have detected errors before gnustep-base ever gets a chance).

**Comment by ngrewe** [comment]
I think your "simple fix" is just the right one – libobjc2 doesn't support binaries mixing modules compiled with pre-2.0 and 2.0 ABIs (`__objc_load()` will abort when it detects that).

Many thanks!
