### ISSUE TITLE
Bus error for timezone access

### ISSUE THREAD

**Issue by rmottola** [gnustep/libs-base#195]
```Starting program: /opt/GNUstep/Local/Tools/Ink 
[Thread debugging using libthread_db enabled]
[New Thread 1 (LWP 1)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 1 (LWP 1)]
-[GSTimeZone initWithName:data:] (self=0x4b3fa8, _cmd=<optimized out>, name=0x114b00, data=<optimized out>)
    at NSTimeZone.m:3067
3067          n_trans = GSSwapBigI32ToHost(*(int32_t*)(void*)header->tzh_timecnt);
```
```(gdb) p  *(struct tzhead *)header
$4 = {tzh_magic = "TZif", tzh_version = "2", tzh_reserved = '\000' <repeats 14 times>, 
  tzh_ttisutcnt = "\000\000\000\b", tzh_ttisstdcnt = "\000\000\000\b", tzh_leapcnt = "\000\000\000", 
  tzh_timecnt = "\000\000\000\252", tzh_typecnt = "\000\000\000\b", tzh_charcnt = "\000\000\000\021"}
```
On Solaris 64bit UltraSPARC

**Comment by rfm** [comment]
> On 30 Jul 2021, at 02:13, Riccardo ***@***.***> wrote:
> 
> 
> [Thread debugging using libthread_db enabled]
> [New Thread 1 (LWP 1)]
> 
> Program received signal SIGSEGV, Segmentation fault.
> [Switching to Thread 1 (LWP 1)]
> -[GSTimeZone initWithName:data:] (self=0x4b3fa8, _cmd=<optimized out>, name=0x114b00, data=<optimized out>)
>     at NSTimeZone.m:3067
> 3067          n_trans = GSSwapBigI32ToHost(*(int32_t*)(void*)header->tzh_timecnt);
> 
> $4 = {tzh_magic = "TZif", tzh_version = "2", tzh_reserved = '\000' <repeats 14 times>, 
>   tzh_ttisutcnt = "\000\000\000\b", tzh_ttisstdcnt = "\000\000\000\b", tzh_leapcnt = "\000\000\000", 
>   tzh_timecnt = "\000\000\000\252", tzh_typecnt = "\000\000\000\b", tzh_charcnt = "\000\000\000\021"}
> 
> On Solaris 64bit UltraSPARC

I'm guessing this is because we have a version 2 file.
In version 1, the header fields are carefully aligned on 4byte boundaries, so we can access them as 32bit inbtegers.
in version 2, we have to use a second header whose position is calculated offset from the first header:
          pos += GSSwapBigI32ToHost(*(int32_t*)(void*)header->tzh_timecnt) * 5
            + GSSwapBigI32ToHost(*(int32_t*)(void*)header->tzh_typecnt) * 6
            + GSSwapBigI32ToHost(*(int32_t*)(void*)header->tzh_charcnt)
            + GSSwapBigI32ToHost(*(int32_t*)(void*)header->tzh_leapcnt) * 8
            + GSSwapBigI32ToHost(*(int32_t*)(void*)header->tzh_ttisstdcnt)
            + GSSwapBigI32ToHost(*(int32_t*)(void*)header->tzh_ttisutcnt);
depending on the values in the fields of the first header, this could mean that the header we are using is no longer 'properly' aligned for sparc

I think to fix that you would need to change the code, from the point where it switches to using the v2 header, to use memcpy to get the data from the buffer rather than expecting a pointer into the buffer to be usable as a pointer to a 32bit integer.

eg.

uint32_t	tmp;
memcpy(&tmp,  header->tzh_timecnt, 4);
n_stans = GSSwapBigI32ToHost(tmp);

**Comment by triplef** [comment]
I think this commit might have fixed this: https://github.com/gnustep/libs-base/commit/e9a21ffd2bf7ada5abe0dd4371476ef94aaad230

Could you try again @rmottola?

**Comment by rmottola** [comment]
I did not write which application I was starting, but I tested and I can start a couple of apps without issues, so I suppose it is fixed.
