### ISSUE TITLE
GSNativeProtocol - 'Task has no original request'

### ISSUE THREAD

**Issue by Zulu-Inuoe** [gnustep/libs-base#302]
I'm getting an assertion failure of "Task has no original request" from [GSNativeProtocol.m, line 395](https://github.com/gnustep/libs-base/blob/82d9917c2c170bda8add53638c41da7235316a6a/Source/GSNativeProtocol.m#LL395C5-L395C5)

Backtracking a bit, I ended up here from a call to [NSURLConnection.m, line 262](https://github.com/gnustep/libs-base/blob/82d9917c2c170bda8add53638c41da7235316a6a/Source/NSURLConnection.m#L262)

The protocol object is created in that same method, just two lines prior, and has `initWithRequest` called on it, but **not** `initWithTask`, at no point is there a task associated with it, so it naturally fails when it goes to `resume`.

I may be blind, but I don't see any way that this could ever have been working, even back to the original commit - 85f590f88e1b462b18f321ae6ae4931852d865e3

Any thoughts?

**Comment by rfm** [comment]
Apple have gone througn three different APIs for managing URLs (NSURLHandle, NSURLConnection, and now NSURLSession).
I'm fairly sure this must have been a case of using two different URL APIs in the same program ... because NSURLConnection belongs to a different group of APIs than GSNativeProtocol (which is used by NSURLSession).
I guess the problem never arose for anyone else because people normally use one generation of the APIs and try to consistently do things the same way.
I think the problem was that a protocol implementation for using tasks in the session API was registered when NSURLSession was used, and then this was mistakenly picked up by the later use of NSURLConnection.
I changed the internals so this should not happen in future, because protocols for NSURLConnection should now implement +canInitWithTask: to return NO and protocols for NSURLSession should implement +canInitWithRequest: to return NO.
