### ISSUE TITLE
NSConcretePointerFunctions implementation is incorrect for non-default options

### ISSUE THREAD

**Issue by brooke-tilley** [gnustep/libs-base#311]
There are some serious issues with the implementation of `NSConcretePointerFunctions`, especially w.r.t. the `NSPointerFunctionsOptions` enum and the initialization of `PFInfo`. I briefly tried to fix these problems locally, but the fixes soon spiraled into fixes to `NSConcreteMapTable`, `NSPropertyList`, and so on; so I'm just going to leave an issue here.

A couple concrete issues that I can be 100% certain about:

 1. The enum values of `NSPointerFunctionsOptions` are not bitfields. In other words, most of the options don't have a mutually-exclusive bitwise representation (they are just sequential integers). However in the vast majority of places that interacts with these options, they are treated as bitfields and bitwise-AND'ed against in an attempt to determine if they are "set". This produces completely unexpected behaviour.
     - I have found instances of this issue in NSConcretePointerFunctions, NSConcreteMapTable, NSConcreteHashTable, and NSPointerArray, but it may occur elsewhere as well.
     - [Here is one small example](https://github.com/gnustep/libs-base/blob/cd231a3efdf766e016f045972eb16ce8c7aab5d8/Source/NSConcreteHashTable.m#L80) of a place where this happens.
 2. The `initWithOptions` function in NSConcretePointerFunctions.m (apart from its issues with said enum values) also does not correctly set the fields of its `PFInfo _x` instance variable. An example of this is the `acquireFunction` function pointer, which doesn't get set based on the Memory flags, but instead gets set based on the Personality flags, [which should only affect](https://developer.apple.com/documentation/foundation/nspointerfunctionsoptions?language=objc) the `hashFunction`, `isEqualFunction`, and `describeFunction` fields. So in many cases, the `acquireFunction` will be mis-set, which can cause all sorts of memory issues (for example, a non-objc pointer could be casted to `id` and then sent a `retain` message).

In addition to those concrete issues, I'm fairly certain that there are some issues with the way that weak pointers are handled, especially in `NSConcreteMapTable` which "overrides" parts of the `NSPointerFunctions` functionality, presumably because it wasn't working. [There is a comment about this from 2013](https://github.com/gnustep/libs-base/blob/cd231a3efdf766e016f045972eb16ce8c7aab5d8/Source/NSConcreteMapTable.m#L107). When I locally tried to patch the `NSConcretePointerFunctions` implementation, it cascaded into spooky memory issues in `NSConcreteMapTable`, `NSPropertyList`, and so on. I assume this is because those implementations have unknowingly been relying on unexpected behaviour from `NSConcretePointerFunctions`.

As mentioned, I am not going to fix these problems myself as the attempted fix grew well outside of my scope, but I'm leaving this issue here because it is a rather large potential source of memory corruption issues, memory leaks, and so on.

**Comment by rfm** [comment]
I thought I had reached out to brooke-tilley last year (to ask for further information) and had no response, but I see nothing attached to the git issue so possibly my email got lost due to an error at my end.
Anyway, I have been reviewing this again and have some observations:
1. the issue with values being treated as bitfields when they are not ... I found a few cases of this (including the example given in this issue), surely a bug, which I have fixed locally and will be testing.   One clear case is in the garbage collection memory boundary setting, but that code is unused (garbage collection is not supported) and harmless:  I'm marking it deprecated so we can remove it in a later release.
2. the -initWithOptions: issue for NSConcretePointerFunctions seems to be a misunderstanding to me.  It is impossible to select memory acquire functions without also considering personality (for instance, NSPointerFunctionsStrongMemory means retain/release for object personality, but not for non-object personalities), and it looks to me that the existing code chooses reasonable functions for the personality/memory type combination.  However, I think we need to test compatibility with OSX to be certain.
3. It would be really good to have some test code demonstrating the examples of 'spooky memory issues'.

**Comment by rfm** [comment]
Closing this as fixed ...
I added some testcases for NSPointerFunctions to check they match OSX.
I have fixed the (very) few cases of incorrectly treating enumeration values like bits in a bitfield.  These were definitely a bug and may have caused any odd behaviors seen.
I didn't find any case of -initWithOptions: doing anything unreasonable, but I did find a few cases where its behavior did not match the undocumented behavior of OSX, and in those cases I changed it to match.
I also made some other tidyups, some changes to match undocumented osx behaviors (passing nil arguments into map tables and pointer arrays is now ignored), and removed/modified a couple of misleading comments.
