### ISSUE TITLE
-[NSTask launch] fails to close all file descriptors in child

### ISSUE THREAD

**Issue by lcampbel** [gnustep/libs-base#345]
Currently `-[NSTask launch]` closes all file descriptors by:
```
      for (i = 3; i < NOFILE; i++)
        {
          (void) close(i);
        }
```
This is wrong, as NOFILE is defined as 256 so we stop at 256, even if there are many more files open. Instead, it should do:
```
      for (i = 3; i < sysconf(_SC_OPEN_MAX); i++)
        {
          (void) close(i);
        }
```

**Comment by rfm** [comment]
Interesting bug, and it appears to be a trickier problem than it looks at first glance.
I found information that using sysconf(_SC_OPEN_MAX) is non-portable because it returns an unusably large value on some systems.
https://stackoverflow.com/questions/899038/getting-the-highest-allocated-file-descriptor
There are various approaches there, but it's not clear what the best option is (or how many different options we need to support).

**Comment by rfm** [comment]
I think using closefrom() where available is probably the best option.

**Comment by rfm** [comment]
Should be fixed now, with a variety of techniques.

**Comment by hmelder** [comment]
Congrats! That was fix.

**Comment by lcampbel** [comment]
Thanks!!!
