### ISSUE TITLE
Writing file atomically vs. not leads to different permissions

### ISSUE THREAD

**Issue by triplef** [gnustep/libs-base#361]
When creating a file using the NSString/NSData methods `writeTo[File|URL]:atomically:encoding:error:` and similar, the resulting file has different permissions depending on whether the `atomically` parameter is yes or no.

- Atomically YES: 0644
- Atomically NO: 0666

When writing atomically we explicitly set a 0644 mask on the temporary file, whereas in the other case the default permissions of `fopen` are used (i.e. the current `umask` value, defaulting to 0666):
https://github.com/gnustep/libs-base/blob/db90ab6bb9e65c6076308234d4e1e21586cbde17/Source/NSData.m#L2014-L2017

I was wondering if there was a reason for this behavior, as I would have expected both cases to behave the same wrt. file permissions (this is also the case on macOS).

**Comment by rfm** [comment]
> On 5 Jan 2024, at 11:33, Frederik Seiffert ***@***.***> wrote:
> 
> 
> When creating a file using the NSString/NSData methods writeTo[File|URL]:atomically:encoding:error: and similar, the resulting file has different permissions depending on whether the atomically parameter is yes or no.
>     • Atomically YES: 0644
>     • Atomically NO: 0666
> When writing atomically we explicitly set a 0644 mask on the temporary file, whereas in the other case the default permissions of fopen are used (i.e. the current umask value, defaulting to 0666):
> https://github.com/gnustep/libs-base/blob/db90ab6bb9e65c6076308234d4e1e21586cbde17/Source/NSData.m#L2014-L2017
> I was wondering if there was a reason for this behavior, as I would have expected both cases to behave the same wrt. file permissions. This is also the case on macOS.

The idea is that atomic writing is supposed to be more secure (avoiding interference during the write), and it's good security practice not to create temporary files that are writable by other people, because there's a window between writing the file and moving it into place in which some other person could modify it.

If the destination file already exists, we set the permissions of the new version to be the same as the old one.

**Comment by triplef** [comment]
Ah I see, that makes sense.

Do you see any issue with changing the permissions to `umask` after renaming the temporary file, so the caller gets the same final permissions irrespective of the atomically flag?

**Comment by rfm** [comment]
> On 5 Jan 2024, at 12:13, Frederik Seiffert ***@***.***> wrote:
> 
> 
> Ah I see, that makes sense.
> Do you see any issue with changing the permissions to umask after renaming the temporary file, so the caller gets the same final permissions irrespective of the atomically flag?
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***>

Sorry to take so long replying ... the more I thought about it, the less sure I was.

I completely understand the feeling that the same final permissions should be produced irrespective if the flag saying whether the operation is atomic or not.

However,  relaxing permissions after the file is created somewhat negates the security rationale for having the file readonly to others in the first place.

If we were writing unix code, we'd expect an operation that created a file to usually match umask, and there's value to sticking with system conventions.

On the other hand, the umask mechanism is an old-fashoned security idea because it's one which can relatively easily be accidentally broken by someone setting a foolish value for umask.

Perhaps more importantly, existing code may be expecting files created by this methof to be secure.

So, while I don't have a lot of confidence in the conclusion, my feeling is that rather than reprotecting the temporary file to relax permissions, we should probably be creating files (when no temporary file is used) with stricter permissions in the case when umask is not set to disallow group/other rwrite permission.

**Comment by triplef** [comment]
Thanks for your thoughts. Personally I always thought the `atomically` flag was just about what it says: writing files atomically, which to me doesn’t seem to say anything about file permissions. It absolutely makes sense that the temporary file should not be accessible by other users, but for the final file I would have expected the API to result in the same permissions as when using any other file writing API in Foundation. Assuming the APIs otherwise behave consistently regarding permissions (which I don’t know) and use `umask` throughout it feels unexpected to me that this flag would result in different permissions.

I do agree that world-writable permissions seem like an odd choice as a default for umask/fopen, and 644 makes more sense, but maybe we can expect developers who this is important to to explicitly set their umask accordingly. If we do want to change the default that should at least be highlighted in the release notes as to me that also seems likely to break things in existing code.

In any case, I don’t actually have a strong opinion here – I just brought it up because we ran into an issue where on Android we were unable to delete some files using `adb` that were written atomically, and I noticed that writing non-atomically fixed this. It’s probably a bit of an edge case but it shows that tighter permissions can also break things.

**Comment by triplef** [comment]
I just came across this note in Apple’s "File System Programming Guide" which seems to confirm we should use umask everywhere?
> Note: Any files you create inherit the permissions associated with the current user and process.

https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/ManagingFIlesandDirectories/ManagingFIlesandDirectories.html#//apple_ref/doc/uid/TP40010672-CH6-SW4

**Comment by rfm** [comment]
Ah, OK then.

**Comment by rfm** [comment]
I changed the code to set the mode to be 0666 with umask applied, as suggested by the Apple documentation.

**Comment by triplef** [comment]
Thank you @rfm. I meant to push a PR for this but got sidetracked...
