### ISSUE TITLE
NSJSONSerialization returns nil for certain strings with Unicode sequences

### ISSUE THREAD

**Issue by triplef** [gnustep/libs-base#365]
The following JSON string causes `NSJSONSerialization` to return nil and a nil error (but works correctly on Apple platforms):

```objc
NSString *json = @"{\"string\": \"DJ TRACKS for the best ELECTRO HOUSE PARTY\\uD83D\\uDD25\\uD83D\\uDD25Shuffle\\uD83D\\uDD00&Shuffle\\uD83D\\uDC5F\\uD83D\\uDC5F\"}";
NSData *data = [json dataUsingEncoding:NSUTF8StringEncoding];
NSError *error = nil;
id obj = [NSJSONSerialization JSONObjectWithData:data options:0 error:&error];
NSLog(@"OBJECT: %@ (%lu, %@)", obj, data.length, error);
```

Output: `OBJECT: (null) (131, (null))`

I wasn’t able to strip the string down further as removing various things from the string make it work correctly, e.g. removing the ampersand but also the text in front of the Unicode characters.

I’m assuming the issue has to do with the Unicode decoding here, but I wanted to see if anyone has an idea what might be going on here before digging in further:
https://github.com/gnustep/libs-base/blob/75fd9549efb07e5d114b7d5e725e1420f1e175c0/Source/NSJSONSerialization.m#L392-L410

**Comment by rfm** [comment]
Thanks ... this was an interesting one.  The GNUstep unicode implementation is quite strict and the NSJSONSerialization code was creating bad strings because it uses a 64 character buffer to create small strings, appending them to build longer ones, without checking the integrity of the parts it was creating, so when the buffer boundary was in the middle of a surrogate pair this would cause the creation of the strings to fail.
I changed the code to check for this case, and defer the first half of the surrogate pair to the next chunk, so as long as the source JSON doesn't contain invalid escape sequences it should be OK.
Please close this issue if you think the fix is correct.

**Comment by triplef** [comment]
Thank you for the quick fix, works great!
