### ISSUE TITLE
subClass of NSHashTable does not call allocWithZone

### ISSUE THREAD

**Issue by wayneyzt** [gnustep/libs-base#393]
There is a subclass that inherits from NSHashTable, and in the subclass, the allocWithZone method and the alloc method are overridden. Why does the alloc method return NSConcreteHashTable and the allocWithZone method of the subclass does not trigger.

**Comment by wayneyzt** [comment]
@implementation MySafeHashTable

+ (instancetype)allocWithZone:(struct _NSZone *)zone {
    MySafeHashTable *hashTable = nil;
    hashTable = [super allocWithZone:zone];
    NSLog(@"%@",NSStringFromClass(self));

    return hashTable;
}

+ (instancetype)alloc {
    __auto_type inst = [super alloc];
    
    return inst;
}


@end

**Comment by rfm** [comment]
> Why does the alloc method return NSConcreteHashTable and the allocWithZone method of the subclass does not trigger.

You implemented +alloc to call the superclass implementation of +alloc instead of +allocWithZone : .... so that's what it does.
If you wanted it to call +allocWithZone: (the normal convention), you should have implemented it to do that.

In your example the sequence of calls (following the rules of the ObjC language) is:
1. +[MySafeHashTable alloc] (calls the superclass alloc)
2. +[NSHashTable +alloc] (calls its allocWithZone:)
3. +[NSHashTable +allocWithZone:] (allocates a concrete class instance)

If you want to allocate an instance of your own class, then your code should (though the implementation of +alloc is redundant) be 

+ (instancetype) allocWithZone: (struct _NSZone *)zone
{
  MySafeHashTable *hashTable = NSAllocateObject(self, 0, zone);
  return hashTable;
}

+ (instancetype) alloc
{
  return [self allocWithZone: NSDefaultMallocZone()];
}

**Comment by wayneyzt** [comment]
@rfm NSAllocateObject cant be used in ARC, is there any other way to allocate an instance?

**Comment by wayneyzt** [comment]
@rfm and what if MySafeHashTable does not implement allocWithZone,like this

@implementation MySafeHashTable


+ (instancetype)alloc {
    return [self allocWithZone:NSDefaultMallocZone()];
}

then it should calls +[NSHashTable +allocWithZone:]  code below

+ (id) allocWithZone: (NSZone*)aZone
{
  if (self == abstractClass)
    {
      return NSAllocateObject(concreteClass, 0, aZone);
    }
  return NSAllocateObject(self, 0, aZone);
}

this self should be MySafeHashTable, not abstractClass,so it can not run into this if condition.
but now it does. Where did I get this wrong?
😭help wanted

**Comment by rfm** [comment]
>  NSAllocateObject cant be used in ARC,
In what way?
When ARC is available,  NSAllocateObject() should be a wrapper round the runtime function class_createInstance() (plus a bit of administrative stuff for memory allocation debugging support).

>  is there any other way to allocate an instance?
Use the objc runtime function directly.
There are other possibilities, best avoided, or only for experts addressing exceptionally unusual situations.

> this self should be MySafeHashTable, not abstractClass,so it can not run into this if condition.
Correct.
> but now it does. Where did I get this wrong?
I think you are mistaken.  The original wrong code called the method on 'super' (in this case NSHashTable), but your revised version calls it on 'self' (MySafeHashTable).  The two different cases should behave differently.

**Comment by rfm** [comment]
Sorry about that last bit ... the self/super part is confused/misleading.
Yes self/super in +alloc makes a difference to what version of the +allocWithZone: method its called, but the behavior you are looking at is controlled by what class the method is called for.  If you call it for NSHashTable then, within the method  self==abstractClass is true, but if you call it for MySafeHashTable then self==abstractClass is false.

**Comment by wayneyzt** [comment]
> Sorry about that last bit ... the self/super part is confused/misleading. Yes self/super in +alloc makes a difference to what version of the +allocWithZone: method its called, but the behavior you are looking at is controlled by what class the method is called for. If you call it for NSHashTable then, within the method self==abstractClass is true, but if you call it for MySafeHashTable then self==abstractClass is false.

I made a simple test.  I call it for MyHashTable, seems self == abstractClass is true
<img width="1071" alt="截屏2024-05-11 22 21 32" src="https://github.com/gnustep/libs-base/assets/11458790/cc909a14-281b-4509-90f5-c918041f4e60">

**Comment by rfm** [comment]
> I made a simple test. I call it for MyHashTable, seems self == abstractClass is true
Then I expect your test is wrong in some way, since a compiler bug is extremely unlikely.
One obvious bug is that you call -init, which may return an instance of another class, before trying to print anything.

A similar simple test program ('general.m') demonstrates things working as expected:

#import <Foundation/Foundation.h>

@interface      MyHashTable : NSHashTable
@end
@implementation MyHashTable
+ (instancetype) alloc
{
  return [self allocWithZone: NSDefaultMallocZone()];
}
@end

void main()
{
  MyHashTable           *t0 = [MyHashTable alloc];
  MyHashTable           *t1 = [t0 init];

  NSLog(@"+alloc %@", [t0 class]);
  NSLog(@"-init %@", [t1 class]);
  NSLog(@"class by property %@", NSStringFromClass(t1.class));
}

and here is the output:

2024-05-11 16:08:18.868 general[934054:934054] +alloc MyHashTable
2024-05-11 16:08:18.869 general[934054:934054] -init MyHashTable
2024-05-11 16:08:18.869 general[934054:934054] class by property MyHashTable

**Comment by wayneyzt** [comment]
> > I made a simple test. I call it for MyHashTable, seems self == abstractClass is true
> > Then I expect your test is wrong in some way, since a compiler bug is extremely unlikely.
> > One obvious bug is that you call -init, which may return an instance of another class, before trying to print anything.
> 
> A similar simple test program ('general.m') demonstrates things working as expected:
> 
> #import <Foundation/Foundation.h>
> 
> @interface MyHashTable : NSHashTable @EnD @implementation MyHashTable
> 
> * (instancetype) alloc
>   {
>   return [self allocWithZone: NSDefaultMallocZone()];
>   }
>   @EnD
> 
> void main() { MyHashTable *t0 = [MyHashTable alloc]; MyHashTable *t1 = [t0 init];
> 
> NSLog(@"+alloc %@", [t0 class]); NSLog(@"-init %@", [t1 class]); NSLog(@"class by property %@", NSStringFromClass(t1.class)); }
> 
> and here is the output:
> 
> 2024-05-11 16:08:18.868 general[934054:934054] +alloc MyHashTable 2024-05-11 16:08:18.869 general[934054:934054] -init MyHashTable 2024-05-11 16:08:18.869 general[934054:934054] class by property MyHashTable


But mine seems not =.=
<img width="1086" alt="截屏2024-05-11 23 31 24" src="https://github.com/gnustep/libs-base/assets/11458790/5b1078e6-ead2-4dd1-b388-fe7aca87f96b">

**Comment by rfm** [comment]
Well the most likely bug in your program is that it's calling a different method implementation.
To debug, you need to create ever simpler/smaller testcases and then step through with a debugger to find exactly where it goes wrong.  For instance, if you have implemented +allocWithZone: for this class somewhere you would remove that implementation to ensure that the normal implementation is used, and if you step through in a debugger, you can spot there unexpected code is being used.

**Comment by wayneyzt** [comment]
> Well the most likely bug in your program is that it's calling a different method implementation. To debug, you need to create ever simpler/smaller testcases and then step through with a debugger to find exactly where it goes wrong. For instance, if you have implemented +allocWithZone: for this class somewhere you would remove that implementation to ensure that the normal implementation is used, and if you step through in a debugger, you can spot there unexpected code is being used.

#import <Foundation/Foundation.h>

@interface MyHashTable : NSHashTable
@end
@implementation MyHashTable

+(instancetype) alloc
{
    id inst = [self allocWithZone:NSDefaultMallocZone()];
    NSLog(@"%@",[inst class]);
    return inst;
}
@end

int main(int argc, const char * argv[]) {
    @autoreleasepool {
        MyHashTable *t0 = [MyHashTable alloc];
        MyHashTable *t1 = [t0 init];

        NSLog(@"+alloc %@", [t0 class]);
        NSLog(@"-init %@", [t1 class]);
        NSLog(@"class by property %@", NSStringFromClass(t1.class));
    }
    return 0;
}

and the output like this:

YES I removed the implementation of +allocWithZone

**Comment by rfm** [comment]
So, now you need to start debugging
eg
check what self is before +allocWithZone: 
check what self is inside +allocWithZone: at the start
check what the version of +allocWithZone: the debugger is examining actually does

**Comment by wayneyzt** [comment]
> So, now you need to start debugging eg check what self is before +allocWithZone: check what self is inside +allocWithZone: at the start check what the version of +allocWithZone: the debugger is examining actually does

"There are differences between Apple's implementation of NSHashTable and GNUstep's, but I cannot see Apple's code. I got it wrong.

**Comment by rfm** [comment]
Just to be clear.  I think you are saying that your tests were on *apple* code, not on GNUstep.  So it's the Apple implementation of +allocWithZone: that's unconditionally returning an instance of NSConcreteHashtable.

I would say that the Apple implementation exhibits poor behavior (because it's unexpected), but not illegal, and the workaround (safe) way to code your class is to use my original suggestion of allocating the instance in your own implementation of +allocWithZone: rather than calling the superclass implementation.

**Comment by wayneyzt** [comment]
> Just to be clear. I think you are saying that your tests were on _apple_ code, not on GNUstep. So it's the Apple implementation of +allocWithZone: that's unconditionally returning an instance of NSConcreteHashtable.
> 
> I would say that the Apple implementation exhibits poor behavior (because it's unexpected), but not illegal, and the workaround (safe) way to code your class is to use my original suggestion of allocating the instance in your own implementation of +allocWithZone: rather than calling the superclass implementation.

appreciate it
