### ISSUE TITLE
NSNotificationCenter removeObserver:name:object: is causing crash

### ISSUE THREAD

**Issue by williameveretteggplant** [gnustep/libs-base#394]
There was a fairly recent addition to NSNotificationCenter.m at the very end of the removeObserver:name:object: method
`if (object_getClass(observer) == GSNotificationObserverClass)
    {
      RELEASE(observer);
    }`
In situations where the observer has already been deallocated (it is a zombie pointer) this will cause a crash. This sometimes occurs in situations where both the observer and the object sending the notification are being released around the same time, and the observer happens to be released first.

I have seen this with TextViews or TableViews that are contained in a NSTabView, which have an NSTabViewController as their delegate. As part of their dealloc, both NSTextView and NSTableView remove the delegate as an observer, but if the NSTabViewController has already been deallocated, it will crash.

This code seems to be written for a special case, and I don't know why exactly it is needed, but as of now, it seems to be a source of instability.

**Comment by triplef** [comment]
This release call will only be used for block observers added with `addObserverForName:object:queue:usingBlock:`, which internally creates a `GSNotificationObserver` object as the observer. We want these object to be released when removing the observer so that they are not leaked.

Are you using block-based observers?

**Comment by williameveretteggplant** [comment]
No. But the object_getClass() call is done every single time. If the pointer is a zombie it crashes.

**Comment by williameveretteggplant** [comment]
I did some test code, and I have confirmed that on Apple you can call removeObserver:name:object: with a zombie pointer

  
    ObserverTestClass *obs = [[ObserverTestClass alloc] init];
    
    [[NSNotificationCenter defaultCenter] addObserver:obs selector:@selector(notificationCalled:) name:@"ANotification" object:nil];
    [obs release];
    
    for (int i=1; i < 20; i++) {
        NSNumber *num = [NSNumber numberWithInt:i];
        NSLog(@"%@", num);
    }
    
    //const char *className = object_getClassName(obs);
    //NSLog(@"class : %s", className);
    
    [[NSNotificationCenter defaultCenter] removeObserver:obs name:@"ANotification" object:nil];
    NSLog(@"finished");`
If I uncomment out the object_getClassName it crashes.

**Comment by rfm** [comment]
You seem to be missing the point: this needs a fix of the root cause of the issue ... the broken code that's producing the illegal value, not find examples where passing the illegal value doesn't happen to cause a crash.

The crash here is in the runtime (not the base library), but it's not the fault of the runtime any more than it's the fault of the base library; both have received a parameter which is *supposed* to be an object (or nil), and neither is responsible for checking that it really *is* an object (or nil), for the simple reason that such a check is too complex and expensive to be done routinely.  The code that produces the illegal value is the code that needs to be fixed.
It's definitely possible to add a check for illegal values (or some other strategy like storing observers in an extra hash table to avoid examining the class of the observer) in lower level code, but doing so would degrade performance and hide the actual bug at the higher level.

**Comment by rfm** [comment]
Here is a link to a nice article giving an idea of the complexity of checking (the mechanisms in the article are not in the least portable) for a bad object pointer:  https://blog.timac.org/2016/1124-testing-if-an-arbitrary-pointer-is-a-valid-objective-c-object/

**Comment by rfm** [comment]
An implementation which would avoid that sort of overhead (though still have some) might work as follows:
When adding the observer,
  obtain lock, add observer address to global hash table, release lock
When removing observer
  obtain lock, test and remove address from global hash table, release lock, if address was found, release observer
That would avoid the dereference of the pointer.

**Comment by rfm** [comment]
While this does look like a clear case of a bug at a higher level, you are not the first person who has said that the GUI API has patterns which make it impossible to write 'correct' code, so I can see a case for helping out in the base library (though I'd still like to know if there are really crashes in multiple cases or its just a bug in one app/class causing crashes).

All that being said, we could add an ivar to hold a hash table or list of known GSNotificationObserver instances and get performance comparable with the use of object_getClass() ... now is the time to break binary compatibility just before a release.

However, if the method was really *meant* to accept non-object pointers I feel that Apple would have documented it as such.  In fact if we are going to make that our behavior we would need to document it as a non-standard behavior, document the fact that we know at least one version of the Apple API does the same thing, and have big loud warnings that Apple may break this in future releases.

**Comment by williameveretteggplant** [comment]
For what it's worth that is how worked for the past 25 years until about 3 months ago.

**Comment by rfm** [comment]
Granted, that does mean there may be 25 years worth of buggy code out in the world, but the fact remains that in general passing an invalid pointer to a function/method has, as part of the programming language, explicitly undefined behavior.  So if we are going to define a new behavior we must document it and warn that it's not portable/safe to rely on.
