### ISSUE TITLE
HTML entities should be used when generating...

### ISSUE THREAD

**Issue by gcasa** [gnustep/libs-base#464]
When generating from GSDOC to HTML entities should be used to prevent parsing errors when loading or generating.   These include ```$%^&*()<>``` (not inclusive) and others.  For instance I had created a comment that had ```<->``` for ```NSUnitConverterLinear``` and this caused a parsing error.  The issue is that no special characters can be used in the comments or it will break parsing.   This should ONLY be a problem with HTML generation.

The issue was it generated the XML, but upon validation, the GSDOC failed due to extraneous characters.   As an example:

```
/**
 * For conversion from C <-> F
 */
```

I was writing the comments for many of these classes and moved that comment to be part of the description of the class and this is where I found the bug.

**Comment by rfm** [comment]
As designed, this is user-error.
  
The content of special comments (those beginning '/**') is expected to be XML (specifically self contained snippets of gsdoc markup) precisely so that the user can mark up their text as they wish.
  

  
The corollary of that design is that, if the user wants to include special characters in their text then they need to use XML entities.
  

  
One alternative would be that autogsdoc would convert special characters to entities and we would need to invent new conventions for users to mark up their text.    That's quite a change (to autogsdoc, to it's spec, and mostly to all the documentation that uses the current markup rules).
  

  
However, another might be that we limit the set of markup elements permitted in comments to a few simple cases (<b>   <term>   </desc>  etc) recognise them specifically, and convert special characters to entities if they are not being used that way.    Possibly messy/confusing due to it's inconsistency.
  

  
Better reporting if user error is another option:    autogsdoc could check that each comment is actually valid XML containing balanced elements (apart from the element marking sections if the source to ignore if course) and report any bad markup with it'd location in the original header/source.
  

  

  
  
  
  
>

**Comment by gcasa** [comment]
Yep. Understood.  With that I will close this.  I wasn't sure if it was something that needs to be fixed or not.
