### ISSUE TITLE
Calling 'mutableBytes' on NSMutableData

### ISSUE THREAD

**Issue by data-forms-action** [gnustep/libs-base#60]
Calling 'mutableBytes' on NSMutableData fails with the following message:

> NSInvalidArgumentException, reason: NSDataStatic(instance) does not recognize mutableBytes

The following sample reproduces the problem:
```
#import <Foundation/Foundation.h>

int main( int argc, const char* argv[] )
{

	char* pStore = malloc( 1024 );

	NSMutableData* dataStore =
		[NSMutableData dataWithBytesNoCopy:pStore
						length:1024
					freeWhenDone:YES];

    // getting bytes.
	char* theData = [dataStore mutableBytes];

	return 0;
}
```

**Comment by tedge** [comment]
Looks like the NSMutableData class is missing an implementation for dataWithBytesNoCopy:length:freeWhenDone:, so calling that method falls through to NSData's implementation, which allocates & returns an NSData object instead of NSMutableData.

As a temporary workaround, replace the dataWithBytesNoCopy:... call with the corresponding initializer (which NSMutableData does implement):
`[[NSMutableData alloc] initWithBytesNoCopy:pStore length:1024 freeWhenDone:YES]`

**Comment by data-forms-action** [comment]
Confirmed, that fixes it as a workaround.

Thanks a lot.
