### ISSUE TITLE
Undefined reference to 'CFStringConvertEncodingToNSStringEncoding'

### ISSUE THREAD

**Issue by mehlkelm** [gnustep/libs-base#98]
I am trying to work with CHCSVParser (https://github.com/davedelong/CHCSVParser/tree/master/CHCSVParser). GNUstep can't compile a file that is referencing CFStringConvertEncodingToNSStringEncoding(), failing with the error 

"Undefined reference to 'CFStringConvertEncodingToNSStringEncoding'"

**Comment by triplef** [comment]
That function is [defined](https://github.com/gnustep/libs-corebase/blob/16c471018babafeea1aa7abac92e628c19d05442/Source/CFStringEncoding.c#L399) in GNUstep CoreBase (aka CoreFoundation).

I think the problem is that the Android example was not linking against CoreBase. I just pushed a [change](https://github.com/gnustep/android-examples/commit/e99b6be17cc5346bd95bc26e00a7fef0433fb68b) to fix this.

**Comment by mehlkelm** [comment]
Indeed! Thanks
